### ISSUE TITLE
editcp does not expose keypad beep settings

### ISSUE THREAD

**Issue by khaytsus** [DaleFarnsworth/codeplug#10]
I do not currently see how to set the keypad tones on/off in editcp.  It does maintain the setting from the radio when read from the radio, but if I turn them on the radio, read from it, then keep using that codeplug without reading from the radio again and I've since disabled keypad beeps on the radio, I found it kept turning them back on because it was still set in the codeplug.  

Of course, reading from the radio and saving the updated codeplug resolves it but would be nice to expose this in the gui.  Hopefully I'm not just missing the option!

**Comment by DaleFarnsworth** [comment]
Fixed in v0.12.4.
