### ISSUE TITLE
editcp does not expose Privacy codes to set in radio

### ISSUE THREAD

**Issue by khaytsus** [DaleFarnsworth/codeplug#12]
Obviously hams can not use privacy codes, however, someone using the radio for commercial use might need privacy codes.  It is exposed at the channel level to pick but you cannot set what the actual code is anywhere that I've seen.  Also, the channel gui does not make it clear you're picking a preconfigured privacy entry but it appears to be freeform, but it only accepts 0-15 as there are only 16 of each type of code available for setting in the radio.  Might be better if that is a -/+ UI like color code.

**Comment by DaleFarnsworth** [comment]
Fixed in v0.12.4.
