### ISSUE TITLE
Add button when duplicating a channel sometimes leaves TX Offset as Invalid

### ISSUE THREAD

**Issue by khaytsus** [DaleFarnsworth/codeplug#16]
If you duplicate a channel by clicking the Add button on an existing channel (Analog, DMR, doesn't seem to matter) the new channel sometimes shows as INVALID.  Sometimes have to click the new channel, then an older one, then back to the new one.  It's a bit of an odd set of reproduction steps but it's pretty easy to reproduce none the less.

I had to add a few, then looked at the new ones and they were fine.  Added a few more, looked, were fine.  Added a few more, then I started seeing ones that were fine previously were now showing as Invalid.

**Comment by DaleFarnsworth** [comment]
Fixed in v0.13.1.  Please test when you get a chance.

**Comment by DaleFarnsworth** [comment]
Closing after not receiving a response.
