### ISSUE TITLE
General Setting Window does not scale to users screen size.

### ISSUE THREAD

**Issue by P3Hosting** [DaleFarnsworth/codeplug#20]
My Laptop is typically set to 1368x768 and when displaying the general settings there is no way to exit or save data. Changing screen resolution will resolve the problem however the type gets a bit hard to read due to my aging eyes. I run Mint Linux 18.3, and v 1.0.0 of editcp
Attached is a screen shot.

Great piece of code. Thanks for your effort
Regards,
George
![image](https://user-images.githubusercontent.com/8807472/48565001-82797780-e8c5-11e8-8c3f-878cc4397e7b.png)

**Comment by DaleFarnsworth** [comment]
Thank you George for taking the time to report this.  I believe the GUI I use (QT5) doesn't permit proportional scaling.  I could reduce the font point size, but that's less than satisfactory.  I decided to reduce the height of the General Settings window by moving several fields from the second column into the third.  The window should fit comfortably in a screen 768 pixels high.  It is available in v1.0.2.
