### ISSUE TITLE
Duplicating a zone, scan list, etc, is creating invalid entries

### ISSUE THREAD

**Issue by khaytsus** [DaleFarnsworth/codeplug#21]
I noticed today when attempting to create a new zone that editcp seems to create a bunch of blank invalid entries in the new zone.  At first they are not visible, but if you save the file, hit Ignore on the errors, then reload edit and load the file again, they show up as invalid.  This happens for Scan and Zone, it might also happen for others but I haven't tried them.

I am able to work around it by deleting a few of the entries, adding in some valid entries, then deleting the remaining invalid entries.  Oddly if I just try to delete all of the invalid entries it entirely breaks the parent entry and I can't add anything to it.  I have to delete it and start over.

I have a codeplug I've been using for a while, updating, writing to my MD-380, so maybe it has some internal issues from being used over various editcp versions.

Reproduction steps are pretty basic, load a codeplug, open Zones, duplicate any Zone.  For giggles I also exported to text and it exported Zones: Name: NewName Channel: "" Channel: "" etc.  All empty names, if the original Zone had 6, there are 6 there etc.  If you can't reproduce I can attach files or do stuff local if useful?  I noticed this on 1.0.3, updated to 1.0.6 and still reproduced it.

**Comment by DaleFarnsworth** [comment]
Thank you.  I'll look into it.

**Comment by DaleFarnsworth** [comment]
Fixed in v1.0.7.

**Comment by khaytsus** [comment]
Yep looks good, thank you Dale!
