### ISSUE TITLE
Can't import unmodified json file

### ISSUE THREAD

**Issue by krisp** [DaleFarnsworth/codeplug#23]
Hello! Cool program, thanks for developing. I am having an issue, however. I pulled in my codeplug using editcp and exported it to json, but I when I try to import that same json file, it crashes. I'll attach my codeplug to see if you can reproduce. 

[codeplug.zip](https://github.com/DaleFarnsworth/codeplug/files/2770627/codeplug.zip)

**Comment by DaleFarnsworth** [comment]
Thanks.  I'll take a look.

**Comment by DaleFarnsworth** [comment]
Fixed in v1.0.11, commit 0f467013763344468990c03913681f252287f679.

Thanks!
