### ISSUE TITLE
JSON Import most channels incorrect GPS Settings

### ISSUE THREAD

**Issue by ReinkNL** [DaleFarnsworth/codeplug#24]
I have an automatic generated JSON file, when I import this file the GUI of EditCP shows every thing as expected, but when written to the radio most channels have incorrect GPS settings in the radio.

I included three files in the zip
1) An example JSON file
2) The rdt codeplug file from the radio after programming the JSON file
3) The rdt codeplug file from the radio after manually (on the radio) editing the channels GPS Settings
[Example Files.zip](https://github.com/DaleFarnsworth/codeplug/files/2808493/Example.Files.zip)

**Comment by DaleFarnsworth** [comment]
Fixed in v1.0.13.  Thank you very much for the bug report.
