### ISSUE TITLE
User database incomplete, compared to that obtained by md380tools.

### ISSUE THREAD

**Issue by aknrdureegaesr** [DaleFarnsworth/codeplug#3]
I used the `editcp` UI to update the user database on my rig.  I listen on the 262 German talkgroup. As it happened, the user with DMR ID 2624560 spoke. The rig did not know that id.

I double-checked with the `user.bin` from `md380tools` file. That one did list 2624560.

So from the outside, it looks like `editcp` uses a different way to obtain the data for the user database, compared with `md380tools`, and `editcp`'s results in incomplete data.

For what it's worth: Neither way seem to dig up the id of the German parrot 262997.

Regards, and thank you for providing fine software! Andreas, DJ3EI

**Comment by DaleFarnsworth** [comment]
Thank you for the report. You can find users database file used by editcp by searching for a file named "usersDB.bin". On my Linux systems it is in "/home/dale/.cache/codeplug/Codeplug Editor/usersDB.bin", and on my Windows 10 system, it is in "c:\Users\dale~\AppData\Codeplug\Codeplug Editor\cache\usersDB.bin". The "European" version (with stripped user names) is in the same directory with the name euroUsersDB.bin. In Windows, you can use wordpad to examine these files. I find this entry in usersDB.bin:
  2624560,DL5KL,Wolfgang,,,,Germany
and for euroUsersDB.bin:
  2624560,DL5KL,,,,,Germany
These match the entries for the original md380tools provided by Travis Goodspeed, KK4VCZ.

I know of other databases which contain additional information:
  2624560,DL5KL,Wolfgang,Bergisch Gladbach,Nordrhein-Westfalen,,Germany

I am in the process of enhancing editcp to use these alternative databases.

I have confirmed that the id 262997 is not in any of the databases that I have seen.

Having said all that, I am aware that the method editcp is using to write the user database is not always reliable. I will leave this issue open until I have made it reliable.

**Comment by aknrdureegaesr** [comment]
I found that file, but it is only 6246 bytes long:

```
andreas@meise:~/.cache/codeplug/Codeplug Editor
$ ls -l; head -5 usersDB.bin ; echo ...;  tail -5 usersDB.bin
insgesamt 8
-rw-r--r-- 1 andreas andreas 6246 Jan 28 15:40 usersDB.bin
6241
4001,TG26312 Berlin-Brandenburg,,,,,
4002,TG26321 Hamburg,,,,,
4003,TG26323 Elbe-Weser,,,,,
4004,TG26361 Hessen,,,,,
...
250997,Parrot Service,Echo Function,,,,Russia
250999,APRS Gate,APRS Function,,,,Russia
284991,Audition App,Audition Function,,,,Bulgaria
284997,Parrot Service,Echo Function,,,,Bulgaria
284999,APRS Gate,APRS Function,,,,Bulgaria
```

**Comment by DaleFarnsworth** [comment]
The short file is the problem. It is missing all of the entries from the MARC database website. perhaps that website was down when you attempted to download it. Please try re-downloading the file with editcp.

**Comment by aknrdureegaesr** [comment]
I deleted the user.bin and took the shortcut of trying without attaching the radio with USB. After progress to 100% (much faster than what I'm used to by md380tools) I get a well-deserved "radio not attached to USB" warning and again only a short file. This time, I remembered to choose "Europe" and what I got was

```
$ LANG=C ls -l
total 8
-rw-r--r-- 1 andreas andreas 6177 Jan 28 15:52 euroUsersDB.bin
```

This is `editcp` 0.10.8.

I guess I'm triggering the reliability issue.

Probably needless to say, but for the record: If the software can't download the entire thing, I much prefer if it errors out. Replacing a dated, but otherwise complete version in the radio with one missing almost everything is not what I want to happen.

**Comment by DaleFarnsworth** [comment]
I completely agree. This is the first time i have heard of this failure mode.  I will publish a new version of editcp very soon that disables the userdb update feature until I can be sure it is reliable. I appreciate the report very much.  Thank you.

**Comment by aknrdureegaesr** [comment]
My 2c: That's clean and clear, but it'd hurt users for whom it presently works.

If you could collect error codes from the individual downloads and display a popup: "Download could not be completed." when any download did not work out, to do so may not be _that_ much more work on your part, but nobody will be worse off than presently.

Just a timid suggestion. Do as you see fit.

**Comment by DaleFarnsworth** [comment]
Yes. I know how to fix it. I just have almost no time now to work on it
now. I'm spending a lot of time with a friend in the hospital after he
suffered a stroke. He has no family nearby and needs my help. I will fix it
as time permits. (Soon)

**Comment by DaleFarnsworth** [comment]
I pushed a version v0.10.9 with some bug fixes, including reporting errors when the download of one of the user database components fails.  Thank you again for reporting this and I apologize for the inconvenience it caused you.  Closing.
