### ISSUE TITLE
Private call contact in a channel does not work (for me).

### ISSUE THREAD

**Issue by aknrdureegaesr** [DaleFarnsworth/codeplug#4]
I'm trying to program a channel so that pressing PTT will give me a private call to a user.

The user I've been choosing for initial experiment is the German parrot 262997. I have a "Call Type: Private" contact for the parrot.

Now I enter a new channel. I copy it from the normal TS2 channel of DB0OUD, my local repeater. 

![grafik](https://user-images.githubusercontent.com/1033352/35481555-352c5742-0426-11e8-9d63-9ea88634ff86.png)

When I send to that channel, the Parrot comes back to me with an extremely short transmission. As if I had touched my PTT only momentarily. My speculation is that the problem is going from my rig to the parrot, not vice versa.

When I stay on that channel, and in addition select the Parrot from my contacts, and then push PTT, all is well.

FWIW: When I stay on that channel, select the Parrot from my contacts, send for a while, then quickly press "back" enough time so that the channel display is displayed, before the Parrot answers, all is well still.

I'm completely unsure whether this is a `editcp` problem or something else, including me goofing.

Regards, and thank you for providing fine software, Andreas, DJ3EI

**Comment by DaleFarnsworth** [comment]
Please supply the codeplug file produced by editcp. I am not experienced enough in DMR to diagnose general problems. All I can do is verify that editcp produces the same codeplug file as that produced by Tytera's CPS software. It would also help if you could confirm that you can use the private call on that repeater if you use a codeplug generated by the standard CPS program.  Thank you.

**Comment by aknrdureegaesr** [comment]
The problem turned out to be lack of knowledge on the part of this `editcp` user.

I have not fully understood the details yet, but one apparently has to watch the group list in a channel even if that channel is intended to connect to a particular user. With a proper group list (some work, some don't) configuring a user works as intended.

Thanks for your patience!
