### ISSUE TITLE
Drag and Drop entries from another codeplug can silently fail to copy

### ISSUE THREAD

**Issue by khaytsus** [DaleFarnsworth/codeplug#7]
I was dragging and dropping between two codeplugs (which, btw thank you, that is awesome) and I found some which wouldn't work.  Just quietly did nothing.  I eventually figured out that the Scan List in the channel I was copying didn't exist in the destination codeplug.  If I created the Scan List (or set it to None in the channel to copy) it worked.  I did not test to see if this also applied to another things like RX Group, Contact Name etc but I would guess it probably does.  I was moving some analog channels into an existing pre-set DMR codeplug I found from one I'd started putting together when I found this.

**Comment by DaleFarnsworth** [comment]
Thank you for the report.  I admit to having done little testing of copying
between codeplugs.  I'll add this to my list of bugs to fix.  Frankly, it
will be a while before I get to it.

Thanks again,
Dale

**Comment by khaytsus** [comment]
Hey no problem Dan, I figure if nothing else this will be a workaround for other folks if they have the same issue hopefully they can find this issue.

Hopefully you're working on new shiny stuff vs not working on it, although I must say, where I've been playing with my MD-380 for 5 or so days now and adding more and more channels, contacts, rearranging zones etc I honestly can't think of much it's missing.  I might log another issue later today though of things in the radio that the editor doesn't expose, hopefully you don't mind that sort of thing.

**Comment by DaleFarnsworth** [comment]
I made some significant improvements to copying between codeplugs in v0.15.9.  I believe this is fixed.  Please re-open this bug it it doesn't work for you.
