### ISSUE TITLE
I will split this repository into multiple repositories

### ISSUE THREAD

**Issue by DaleFarnsworth** [DaleFarnsworth/codeplug#8]
I will soon create multiple repositories to hold the code that is currently contained in this single repository.  At least the following repositories will be included.
  editcp - The codeplug editor GUI program
  codeplug-ui - A library containing the codeplug UI elements used by editcp.
  dmrRadio - The CLI program for reading/writing firmware/codeplugs from/to a radio
  codeplug - A library dealing with the manipulation of a codeplug.
  userdb - A library handling the user database used by the MD380.
  radio - A library for reading/writing the flash (including SPI flash) memory of the MD380.
  genFileData - A program for creating a go source file containing the data from a binary file.

**Comment by williamh** [comment]
I've been asked to package this software for Gentoo Linux, and this split would help with that very much.

**Comment by ZeroChaos-** [comment]
Pretty pretty please, I have lots of users that want this software and this will help make it more accessible to them.

**Comment by williamh** [comment]
Another reason to do this is so your software will be able to work with go modules [1]. GOPATH is irrelivent in this case.

[1] https://github.com/golang/go/wiki/Modules

**Comment by DaleFarnsworth** [comment]
I think it's independent  of go modules, though making it independent of GOPATH will be an improvement.  I can see value in separating out the libraries; that's why the issue exists.  I'll give it another try in the next week or so.  My first attempt failed, but it should be simpler now that development has slowed.

**Comment by DaleFarnsworth** [comment]
I have no immediate plans to implement this.  Maybe I'll get to it someday.

**Comment by DaleFarnsworth** [comment]
I have now split this repository into several repositories in github.com/DaleFarnsworth-DMR.  Further development will now occur in those repositories and this repository is now archival.
