### ISSUE TITLE
editcp allows setting digital channels to 25khz

### ISSUE THREAD

**Issue by khaytsus** [DaleFarnsworth/codeplug#9]
This is pretty picky, but small quirk in the editor that doesn't disallow setting a digital channel to 25khz.  It really should disable the option or only offer 12.5khz.

I've tested it and there does not seem to be any ill effect from attempting to set a channel to 25khz.  The radio programs fine, still transmits the expected 12.5khz deviation, other radios receive just fine.

**Comment by DaleFarnsworth** [comment]
Fixed in v0.12.4.
